# Generated by Django 2.2.7 on 2019-11-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_auto_20191124_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(related_name='_twitteruser_following_+', to='twitterclone.TwitterUser'),
        ),
    ]
