# Generated by Django 2.2.7 on 2019-11-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_twitteruser_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='TweetAuthor',
            new_name='tweet_author',
        ),
    ]
